In [1]:
%reset -f

# So-called Australia's Doughnut V1

The basic idea of these script is to collect and clean the data necessary to quantify the doughnut for so-called Australia. 

I will be trying to collect as much time series data as I can for each key social and ecological indicator using the framework outlined in [this paper](https://media.springernature.com/original/springer-static/esm/art%3A10.1038%2Fs41586-025-09385-1/MediaObjects/41586_2025_9385_MOESM1_ESM.pdf). The table below details all the key data sources identified so far: 

|  Social/Ecological   | Dimension | Description    |  Source    | Accessed | Included? |
|:----|:----| :---- | :----: | :---: | :---: |
| Social | Food | Prevelance of Undernourishment *(SDG 2.1.1)* |  [FAO](https://www.fao.org/sustainable-development-goals-data-portal/data/indicators/2.1.1-prevalence-of-undernourishment/en)  | 03/08/2026 | No |
| Social | Food | Population with moderate to severe food insecurity *(SDG 2.1.2)*| [FAO](https://www.fao.org/sustainable-development-goals-data-portal/data/indicators/212-prevalence-of-moderate-or-severe-food-insecurity-in-the-population-based-on-the-food-insecurity-experience-scale/en) |  03/08/2026 |  Yes |
| Social | Health | Under 5 Mortality Rate per 1,000 live births *(SDG 3.2.1)*|  [SDGD](https://unstats.un.org/sdgs/dataportal/database)    | 03/08/2026  |  Yes |
| Social | Health | Universal Health Coverage Index *(SDG 3.8.1)* |  [SDGD](https://unstats.un.org/sdgs/dataportal/database)    | 03/08/2026  |  Yes |
| Social | Education | Proportion of students with low skills in reading, mathetmatics and science *(SDG 4.6)* |  [OECD](https://data-explorer.oecd.org/)    | 03/08/2026  |  Yes |
| Social | Education | Proportion of adults with low numeracy skills *(SDG 4.6)* |  [OECD](https://data-explorer.oecd.org/)    | 03/08/2026  |  No |
| Social | Education | Completion rate of Secondary Education *(SDG 4.1.2)* |  [SDGD](https://unstats.un.org/sdgs/dataportal/database)    |  03/08/2026 |  Yes |
| Social | Income and Work | Proportion of people living below 50% of median income *(SDG 10.2.1)*  |   [WB](https://databank.worldbank.org/source/world-development-indicators#)   | 03/08/2026  | Yes |
| Social | Income and Work | Proportion of youth not in employment, education or training *(SDG 8.6.1)* |   [OECD](https://data-explorer.oecd.org/)    | 03/08/2026 |  Yes |
| Social | Water & Sanitation | Access to Safe Water *(SDG 6.1.1)* |  [SDGD](https://unstats.un.org/sdgs/dataportal/database)    | 03/08/2026  | Yes |
| Social | Water & Sanitation | Access to sanitation *(SDG 6.2.1)* |   [SDGD](https://unstats.un.org/sdgs/dataportal/database)   |  03/08/2026 | Yes |
| Social | Energy |   Access to Electricity *(SDG 7.1.1)* |  [SDGD](https://unstats.un.org/sdgs/dataportal/database)    | 03/08/2026  | Yes |
| Social | Energy |   Clean Fuel & Energy for cooking, heating and lighting *(SDG 7.1.2)* |   [SDGD](https://unstats.un.org/sdgs/dataportal/database)  | 03/08/2026  | Yes |
| Social | Conectivity |  Access to Public Transport in Urban Areas *(SDG 11.2.1)* |   [SDGD](https://unstats.un.org/sdgs/dataportal/database)   |  03/08/2026 | Yes |
| Social | Conectivity | Access to the Internet *(SDG 17.8.1)* |  [SDGD](https://unstats.un.org/sdgs/dataportal/database)|  03/08/2026 | Yes |
| Social | Housing |  Proportion of the urban population living in slums or informal settlements *(SDG 11.1.1)*|  [SDGD](https://unstats.un.org/sdgs/dataportal/database) | 03/08/2026  | No |
| Social | Housing | Proportion of people in greatest need on social housing wait lists | [AIHW](https://www.aihw.gov.au/reports/housing-assistance/housing-assistance-in-australia-2023/contents/households-and-waiting-lists) | 03/08/2026  | Yes |
| Social | Equality | Gender Inequality Index *(SDG 5)*| [HDR](https://hdr.undp.org/data-center/specific-country-data#/countries/AUS) | 03/08/2026  | Yes |
| Social | Equality | Difference in imprisonment rate per 100,000 between Indigenous and Non-indingeous Australians |[PC](https://www.pc.gov.au/closing-the-gap-data/dashboard/outcome-area/criminal-justice/)  |  03/08/2026 | Yes |
| Social | Social Cohesion | Lack of Social Support - proportion of population saying they have no one to help in a time of need | [OECD](https://data-explorer.oecd.org/) | 03/08/2026  | Yes |
| Social | Social Cohesion | Income Inequality as measure by the Palma ratio (total income of top 10% divided by total income of bottom 40% of income earners. | [OWID](https://ourworldindata.org/grapher/palma-ratio-wid?tab=line&country=%7EAUS&mapSelect=%7EAUS&welfare_type=before_tax) | 03/08/2026 | Yes |
| Social | Political Voice | Proportion of people stating they have No Say in Government | [OECD](https://data-explorer.oecd.org/) | 03/08/2026  | Yes |
| Social | Peace & Justice | Homicide Rates per 100,000 *(SDG 16.1.1)* | [SDGD](https://unstats.un.org/sdgs/dataportal/database) | 03/08/2026  | Yes |
| Ecological | Climate Change | Consumption of Co2 Emissions per capita |[OWID](https://ourworldindata.org/grapher/consumption-co2-per-capita?tab=line&country=~AUS&mapSelect=~AUS)  | 03/08/2026 | Yes |
| Ecological | Ocean Acidification | Mean aragonite saturation $\Omega_{arag}$| [AODN](https://portal.aodn.org.au/search?uuid=89b495cc-7382-43c0-abef-d1e66738a924) | 02/08/2026 | Yes |
| Ecological | Chemical Pollution | Material Footprint |[GMFD](https://www.resourcepanel.org/global-material-flows-database)  | 03/08/2026 | Yes |
| Ecological | Nutrient Pollution | Fertiliser Consumption per Capita per Year |[OWID](https://ourworldindata.org/grapher/fertilizer-total-use?country=~AUS)  | 03/08/2026 | Yes |
| Ecological | Air Pollution  | Mean Annual Exposure per cubic micrograms of PM2.5 Pollution|[OWID](https://ourworldindata.org/grapher/average-exposure-pm25-pollution?tab=line&country=~AUS&mapSelect=~AUS)  | 03/08/2026 | Yes |
| Ecological | Freshwater Disruption | No Indicator| [NA]() | NA | No |
| Ecological | Land Conversion | Proportion of landmass remaining forested |[WB](https://databank.worldbank.org/source/world-development-indicators#)  | 03/08/2026 | Yes |
| Ecological | Biodiversity Breakdown | # of Species that are threatened |[WB](https://databank.worldbank.org/source/world-development-indicators#)  | 03/08/2026 | No |
| Ecological | Ozone Layer Depletion | Consumption of ozone depleting substances | [OWID]( https://ourworldindata.org/grapher/ozone-depleting-substance-consumption?country=~AUS) | 03/08/2026 | No |

Further descriptions of each indicator as expanded on below. Furthermore, the following code seeks to clean up all the key datasets before combining into the a final dataset for calculating boundaries. The final analysis is then completed in `R`.

In [2]:
import pandas as pd
import numpy as np
import datetime as dt

In [3]:
# setting filtering list now for final saved dataframe
final_col_list = ['domain', 'dimension', 'indicator', 'Date', 'value', 'boundary']

input_path = "/home/michael/Projects/aus_doughnut/"

# Social Indicators

## Food

### Prevalence of undernourishment
The prevalence of undernourishment (PoU) is an estimate of the proportion of the population whose habitual food consumption is insufficient to provide the dietary energy levels that are required to maintain a normal active and healthy life. It is expressed as a percentage. This indicator will measure progress towards SDG Target 2.1.

https://www.fao.org/sustainable-development-goals-data-portal/data/indicators/2.1.1-prevalence-of-undernourishment/en

This measure is not very interesting for Australia because the actual value is no doubt less than the 2.5 estimate provided. But I assume the precision of the estimate was not high enough to provide a lower estimate with enough confidence. I will not include it in the analysis.

In [4]:
under_nourish = pd.read_csv(input_path + "social/1_food/prevelance_undernourishment.csv")
under_nourish = under_nourish[['TIME_PERIOD','OBS_VALUE']]

under_nourish['Date'] = under_nourish['TIME_PERIOD']
under_nourish['domain'] = "social"
under_nourish['dimension'] = "food"
under_nourish['indicator'] = "prev_undernourishment"
under_nourish['value'] = under_nourish['OBS_VALUE'].str.replace("<","").astype(float)

under_nourish.dropna()

,TIME_PERIOD,OBS_VALUE,Date,domain,dimension,indicator,value
1,2001,<2.5,2001,social,food,prev_undernourishment,2.5
2,2002,<2.5,2002,social,food,prev_undernourishment,2.5
3,2003,<2.5,2003,social,food,prev_undernourishment,2.5
4,2004,<2.5,2004,social,food,prev_undernourishment,2.5
5,2005,<2.5,2005,social,food,prev_undernourishment,2.5
6,2006,<2.5,2006,social,food,prev_undernourishment,2.5
7,2007,<2.5,2007,social,food,prev_undernourishment,2.5
8,2008,<2.5,2008,social,food,prev_undernourishment,2.5
9,2009,<2.5,2009,social,food,prev_undernourishment,2.5
10,2010,<2.5,2010,social,food,prev_undernourishment,2.5
11,2011,<2.5,2011,social,food,prev_undernourishment,2.5
12,2012,<2.5,2012,social,food,prev_undernourishment,2.5
13,2013,<2.5,2013,social,food,prev_undernourishment,2.5
14,2014,<2.5,2014,social,food,prev_undernourishment,2.5
15,2015,<2.5,2015,social,food,prev_undernourishment,2.5
16,2016,<2.5,2016,social,food,prev_undernourishment,2.5
17,2017,<2.5,2017,social,food,prev_undernourishment,2.5
18,2018,<2.5,2018,social,food,prev_undernourishment,2.5
19,2019,<2.5,2019,social,food,prev_undernourishment,2.5
20,2020,<2.5,2020,social,food,prev_undernourishment,2.5
21,2021,<2.5,2021,social,food,prev_undernourishment,2.5
22,2022,<2.5,2022,social,food,prev_undernourishment,2.5
23,2023,<2.5,2023,social,food,prev_undernourishment,2.5
24,2024,<2.5,2024,social,food,prev_undernourishment,2.5

### Population with moderate to severe food insecurity

SDG indicator 2.1.2 Prevalence of moderate or severe food insecurity in the population, based on the Food Insecurity Experience Scale

https://www.fao.org/sustainable-development-goals-data-portal/data/indicators/212-prevalence-of-moderate-or-severe-food-insecurity-in-the-population-based-on-the-food-insecurity-experience-scale/en

It is a quantitative measure of food insecurity derived from 8 qualitative and quantitative questions regarding sufficient access to food. It uses the self-reported Food Insecurity Experience Scale (FIES) standard.

Because it is self-reported it can be a slightly biased measure due to coginitive heuristics. However, it conveys what we are trying to measure.

The social foundation for food insecurity is zero.

In [5]:
food_insecure = pd.read_csv(input_path + "social/1_food/food_insecurity.csv")

food_insecure = food_insecure[['TIME_PERIOD','OBS_VALUE']]

food_insecure['Date'] = food_insecure['TIME_PERIOD']
food_insecure['domain'] = "social"
food_insecure['dimension'] = "food"
food_insecure['indicator'] = "food_insecurity"
food_insecure['value'] = food_insecure['OBS_VALUE']
food_insecure['boundary'] = 0

food_insecure[final_col_list].dropna().sort_values("Date").reset_index(drop=True)

   domain dimension        indicator  Date  value  boundary
0  social      food  food_insecurity  2015   10.8         0
1  social      food  food_insecurity  2016   11.8         0
2  social      food  food_insecurity  2017   12.7         0
3  social      food  food_insecurity  2018   13.3         0
4  social      food  food_insecurity  2019   12.3         0
5  social      food  food_insecurity  2020   11.9         0
6  social      food  food_insecurity  2021   11.4         0
7  social      food  food_insecurity  2022   12.9         0
8  social      food  food_insecurity  2023   13.8         0
9  social      food  food_insecurity  2024   15.1         0

In [6]:
food_insecure[final_col_list].dropna().sort_values("Date").reset_index(drop=True).to_csv(input_path +  "/social/clean/food_insecure_clean.csv", index = False)

## Health

### Under 5 Mortality Rate 
Population living in countries with under-five mortality rate exceeding 25 per 1,000 live births 

Source: https://unstats.un.org/sdgs/dataportal/database

The probability of dying before the age of five. social foundation of 25 per 1,000 lives biths is identified in SDG 3.2.1. Given Australia's very low child mortality and relatively high access to quality healthcare, the foundation for Aus should functionally be zero. I will adopt 1 for the purposes of this analysis.

In [7]:
mort_rate = pd.read_csv(input_path + "social/2_Health/under_five_mortality_rate.csv")

mort_rate['Date'] = mort_rate['Year']
mort_rate['domain'] = "social"
mort_rate['dimension'] = "health"
mort_rate['indicator'] = "under_5_mort_Rate_per_1000_live_births"
mort_rate['value'] = mort_rate['Under_five_mortality_rate_deaths_per_1000_live_births'].astype(float)
mort_rate['boundary'] = 1

mort_rate[final_col_list]

,domain,dimension,indicator,Date,value,boundary
0,social,health,under_5_mort_Rate_per_1000_live_births,2000,6.191880,1
1,social,health,under_5_mort_Rate_per_1000_live_births,2001,6.077458,1
2,social,health,under_5_mort_Rate_per_1000_live_births,2002,5.983027,1
3,social,health,under_5_mort_Rate_per_1000_live_births,2003,5.908929,1
4,social,health,under_5_mort_Rate_per_1000_live_births,2004,5.831027,1
5,social,health,under_5_mort_Rate_per_1000_live_births,2005,5.723941,1
6,social,health,under_5_mort_Rate_per_1000_live_births,2006,5.582402,1
7,social,health,under_5_mort_Rate_per_1000_live_births,2007,5.412019,1
8,social,health,under_5_mort_Rate_per_1000_live_births,2008,5.215773,1
9,social,health,under_5_mort_Rate_per_1000_live_births,2009,5.000088,1
10,social,health,under_5_mort_Rate_per_1000_live_births,2010,4.766182,1
11,social,health,under_5_mort_Rate_per_1000_live_births,2011,4.532051,1
12,social,health,under_5_mort_Rate_per_1000_live_births,2012,4.314756,1
13,social,health,under_5_mort_Rate_per_1000_live_births,2013,4.127336,1
14,social,health,under_5_mort_Rate_per_1000_live_births,2014,3.980898,1
15,social,health,under_5_mort_Rate_per_1000_live_births,2015,3.883152,1
16,social,health,under_5_mort_Rate_per_1000_live_births,2016,3.827957,1
17,social,health,under_5_mort_Rate_per_1000_live_births,2017,3.801625,1
18,social,health,under_5_mort_Rate_per_1000_live_births,2018,3.792095,1
19,social,health,under_5_mort_Rate_per_1000_live_births,2019,3.786012,1
20,social,health,under_5_mort_Rate_per_1000_live_births,2020,3.773206,1
21,social,health,under_5_mort_Rate_per_1000_live_births,2021,3.747973,1
22,social,health,under_5_mort_Rate_per_1000_live_births,2022,3.711634,1
23,social,health,under_5_mort_Rate_per_1000_live_births,2023,3.664211,1
24,social,health,under_5_mort_Rate_per_1000_live_births,2024,3.606601,1

In [8]:
mort_rate[final_col_list].to_csv(input_path +  "/social/clean/under_5_mort_rate_clean.csv", index = False)

### Universal Health Coverage

Source: https://unstats.un.org/sdgs/dataportal/database

The World Health Organisation has created the Universal Health Coverage (UHC) index. UHC is a geometric mean of 14 different proxy variables. The boundary set in the proportion of the worlds population living in a country with a UHC less than 60. 

The available data does not allow for this sort of comparison. Therefore, I will adopt a UHC of 95 as the foundation for Australia considering the various troubles relating to bulk billing and access to healthcare services in Aus. I admit this is an arbitrary choice, however I don't have the time (for now) to derive another foundation.

In [9]:
uhc_df = pd.read_csv(input_path + "social/2_Health/universal_health_coverage.csv")
uhc_df.head()

uhc_df['Date'] = uhc_df['Year']
uhc_df['domain'] = "social"
uhc_df['dimension'] = "health"
uhc_df['indicator'] = "universal_health_coverage_index"
uhc_df['value'] = uhc_df['Universal_health_coverage_service_coverage_index'].astype(float)
uhc_df['boundary'] = 95

uhc_df[final_col_list]

    domain dimension                        indicator  Date  value  boundary
0   social    health  universal_health_coverage_index  2000   84.0        95
1   social    health  universal_health_coverage_index  2001   85.0        95
2   social    health  universal_health_coverage_index  2002   85.0        95
3   social    health  universal_health_coverage_index  2003   86.0        95
4   social    health  universal_health_coverage_index  2004   86.0        95
5   social    health  universal_health_coverage_index  2005   86.0        95
6   social    health  universal_health_coverage_index  2006   86.0        95
7   social    health  universal_health_coverage_index  2007   87.0        95
8   social    health  universal_health_coverage_index  2008   87.0        95
9   social    health  universal_health_coverage_index  2009   87.0        95
10  social    health  universal_health_coverage_index  2010   88.0        95
11  social    health  universal_health_coverage_index  2011   88.0        95
12  social    health  universal_health_coverage_index  2012   89.0        95
13  social    health  universal_health_coverage_index  2013   89.0        95
14  social    health  universal_health_coverage_index  2014   89.0        95
15  social    health  universal_health_coverage_index  2015   89.0        95
16  social    health  universal_health_coverage_index  2016   89.0        95
17  social    health  universal_health_coverage_index  2017   89.0        95
18  social    health  universal_health_coverage_index  2018   89.0        95
19  social    health  universal_health_coverage_index  2019   89.0        95
20  social    health  universal_health_coverage_index  2020   89.0        95
21  social    health  universal_health_coverage_index  2021   89.0        95
22  social    health  universal_health_coverage_index  2022   89.0        95
23  social    health  universal_health_coverage_index  2023   89.0        95

In [10]:
uhc_df[final_col_list].to_csv(input_path +  "/social/clean/uhc_clean.csv", index = False)

## Education
### Illiteracy Rate
Proportion of Adult population (aged 15+) who are illiterate. Aus doesn't have time series data for this measure. Only some cross-sectional surveys.

https://www.abs.gov.au/statistics/people/education/programme-international-assessment-adult-competencies-australia/latest-release#data-downloads

Therefore, I will test the proportion of students with low skills in reading, mathematics and science which currently has two observations. Adults with low numeracy skills only has one observation. I will interpolate and extrapolate the proportion of students with low skills variable before conducting analayis. This data is obviously insufficient for identifying any robust insights, however is the only data currently available. 

Both from: https://data-explorer.oecd.org/
- Students with low skills in reading, mathematics and science
- Adults with low numeracy skills

The foundation for this should be zero in Aus, and relates to SDG 4.6 for achieving literacy and numeracy for youth and adults.

In [11]:
temp = pd.read_csv(input_path + "social/3_education/perc_low_educ.csv")

### Students with low skills in reading, mathematics and science

In [12]:
student_low = temp[temp['Measure'] == "Students with low skills in reading, mathematics and science"]
student_low['Date'] = student_low['TIME_PERIOD']
student_low['domain'] = "social"
student_low['dimension'] = "education"
student_low['indicator'] = "perc_students_low_scores"
student_low['value'] = student_low['OBS_VALUE'].astype(float)
student_low['boundary'] = 0

student_low[final_col_list].sort_values("Date").reset_index(drop=True)

   domain  dimension                 indicator  Date      value  boundary
0  social  education  perc_students_low_scores  2018  11.215180         0
1  social  education  perc_students_low_scores  2022  12.082763         0

In [13]:
student_low[final_col_list].sort_values("Date").reset_index(drop=True).to_csv(input_path +  "/social/clean/perc_low_skills_clean.csv", index = False)

### Adults with low numeracy skills

In [14]:
adults_low = temp[temp['Measure'] == "Adults with low numeracy skills"]
adults_low['Date'] = adults_low['TIME_PERIOD']
adults_low['domain'] = "social"
adults_low['dimension'] = "education"
adults_low['indicator'] = "adults_with_low_numeracy_skills"
adults_low['value'] = adults_low['OBS_VALUE'].astype(float)

adults_low.sort_values("Date").reset_index(drop=True)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,MEASURE,Measure,UNIT_MEASURE,Unit of measure,...,Unit multiplier,DECIMALS,Decimals,BASE_PER,Base period,Date,domain,dimension,indicator,value
0,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,6_4_DEP,Adults with low numeracy skills,PT_ST,Percentage of students,...,Units,2,Two,_Z,NaN,2012,social,education,adults_with_low_numeracy_skills,11.116686

In [15]:
del temp

### Secondary Education
SDG 4.1.2 relates to the completion rate of upper secondary education. The indicator measures the young adult population (aged 21–23) with incomplete upper secondary education.

Source: https://unstats.un.org/sdgs/dataportal/database

Foundation choosen in the research is zero (or 100%) i.e. everyone has at least completed a secondary level of education.

This data will be be interpolated and extrapolated prior to final analysis.

In [16]:
second_educ = pd.read_csv(input_path + "social/3_education/upper_secondary.csv")
second_educ.head()

second_educ['Date'] = second_educ['Year']
second_educ['domain'] = "social"
second_educ['dimension'] = "education"
second_educ['indicator'] = "secondary_educ_completion_rate"
second_educ['value'] = second_educ['Upper_Secondary_Completion_rate'].astype(float)
second_educ['boundary'] = 100

second_educ[final_col_list]

   domain  dimension                       indicator  Date  value  boundary
0  social  education  secondary_educ_completion_rate  2010  85.02       100
1  social  education  secondary_educ_completion_rate  2014  86.65       100
2  social  education  secondary_educ_completion_rate  2016  87.30       100
3  social  education  secondary_educ_completion_rate  2018  90.31       100

In [17]:
second_educ[final_col_list].to_csv(input_path +  "/social/clean/perc_secondary_educ_complt_rate_clean.csv", 
                                   index = False)

## Income and Work

### Poverty
Research has suggestsed a worldwide absolute poverty measure being the population living below the societal poverty line, set at half their country’s median household income or at least $15 a day (Source: [WB](https://www.worldbank.org/en/publication/poverty-and-shared-prosperity-2018)).

In Aus the $15/day line might be a bit low considering the higher prices of some essential basic goods. The paper set so-called Australia's poverty line at 50\% of the median household income but did not provide a specific dollar per day figure *(only noting that for the wealth countries the figure randed from 20-35 dollars per day)*. 

The data on the proportion of the populaiton living below 50\% of the median income from the world development indicators datbases, is relatively incomplete and therefore I will have to interpolate and extrapolate this data before final analysis.

Source: https://databank.worldbank.org/source/world-development-indicators#

The foundation for the poverty rate is zero percent.

In [18]:
poverty = pd.read_csv(input_path + "social/4_income_work/prop_people_living_below_median_income.csv")

poverty['Date'] = poverty['Time']
poverty['domain'] = "social"
poverty['dimension'] = "income and work"
poverty['indicator'] = "prop_pop_living_below_median_income"
poverty['value'] = poverty['Prop_pop_living_below_50_perc_median_inc'].astype(float)
poverty['boundary'] = 0

poverty[final_col_list]

,domain,dimension,indicator,Date,value,boundary
0,social,income and work,prop_pop_living_below_median_income,2001,10.2,0
1,social,income and work,prop_pop_living_below_median_income,2003,10.3,0
2,social,income and work,prop_pop_living_below_median_income,2004,9.6,0
3,social,income and work,prop_pop_living_below_median_income,2008,10.2,0
4,social,income and work,prop_pop_living_below_median_income,2010,10.5,0
5,social,income and work,prop_pop_living_below_median_income,2014,9.8,0
6,social,income and work,prop_pop_living_below_median_income,2016,10.7,0
7,social,income and work,prop_pop_living_below_median_income,2018,11.7,0
8,social,income and work,prop_pop_living_below_median_income,2020,11.3,0

In [19]:
poverty[final_col_list].to_csv(input_path +  "/social/clean/prop_pop_below_median_inc_clean.csv", index = False)

### Youth Opportunities

This measure tracks the proportion of young people (aged 15–24) not in employment, education, or training, or Youth NEET for short. The basic idea behind this measure is to determine the number of opportunities available to young people to avoid poverty i.e. either in work, training for work or recieving an education. This is a crude measure *(it does not account for caring labour/work)* but there is available data on this for Aus and the world, hence it's adoption.

Source: https://data-explorer.oecd.org/

The foundation for Youth NEET is zero percent.

In [20]:
neet_df = pd.read_csv(input_path + "social/4_income_work/youth_unemp_neet_oecd.csv")

neet_df['Date'] = neet_df['TIME_PERIOD']
neet_df['domain'] = "social"
neet_df['dimension'] = "income and work"
neet_df['indicator'] = "youth_neet"
neet_df['value'] = neet_df['OBS_VALUE'].astype(float)
neet_df['boundary'] = 0

neet_df[final_col_list].sort_values("Date").reset_index(drop=True)

    domain        dimension   indicator  Date      value  boundary
0   social  income and work  youth_neet  2004   9.926181         0
1   social  income and work  youth_neet  2005   9.554185         0
2   social  income and work  youth_neet  2006   9.315417         0
3   social  income and work  youth_neet  2007   8.651760         0
4   social  income and work  youth_neet  2008   8.552238         0
5   social  income and work  youth_neet  2009   9.996901         0
6   social  income and work  youth_neet  2010   9.690154         0
7   social  income and work  youth_neet  2011   9.868906         0
8   social  income and work  youth_neet  2012   9.856607         0
9   social  income and work  youth_neet  2013  10.852316         0
10  social  income and work  youth_neet  2014  10.389955         0
11  social  income and work  youth_neet  2015   9.758269         0
12  social  income and work  youth_neet  2016   8.927470         0
13  social  income and work  youth_neet  2017   8.663326         0
14  social  income and work  youth_neet  2018   8.840809         0
15  social  income and work  youth_neet  2019   8.656465         0
16  social  income and work  youth_neet  2020  11.860934         0
17  social  income and work  youth_neet  2021   8.460814         0
18  social  income and work  youth_neet  2022   7.831167         0
19  social  income and work  youth_neet  2023   7.491409         0
20  social  income and work  youth_neet  2024   8.511607         0

In [21]:
neet_df[final_col_list].sort_values("Date").reset_index(drop=True).to_csv(input_path +  "/social/clean/Youth_NEET_clean.csv",
                                                                          index = False)

## Water & Sanitation

### Safe Water

Access to clean drinking water is essential to a good quality of life. Hence it's inclusion as a measure. This indicator measures the proportion of people with access to safe water for drinking, bathing, washing clothes etc. It does not necessarily consider the quality of the water such as the number of microplastics in local water. 

Access to safe water isrelated to the SDG 6.1.1.

Source: https://unstats.un.org/sdgs/dataportal/database

The foundation for access safe water is 100%.

In [22]:
safe_water = pd.read_csv(input_path + "social/5_water_sanitation/safe_water.csv")

safe_water['Date'] = safe_water['Year']
safe_water['domain'] = "social"
safe_water['dimension'] = "water and sanitation"
safe_water['indicator'] = "safe_Water"
safe_water['value'] = safe_water['Prop_pop_safe_water'].astype(float)
safe_water['boundary'] = 100

safe_water[final_col_list]

    domain             dimension   indicator  Date      value  boundary
0   social  water and sanitation  safe_Water  2000  98.288483       100
1   social  water and sanitation  safe_Water  2001  98.288483       100
2   social  water and sanitation  safe_Water  2002  98.288483       100
3   social  water and sanitation  safe_Water  2003  98.420494       100
4   social  water and sanitation  safe_Water  2004  98.552528       100
5   social  water and sanitation  safe_Water  2005  98.684586       100
6   social  water and sanitation  safe_Water  2006  98.816666       100
7   social  water and sanitation  safe_Water  2007  98.948776       100
8   social  water and sanitation  safe_Water  2008  99.080902       100
9   social  water and sanitation  safe_Water  2009  99.213058       100
10  social  water and sanitation  safe_Water  2010  99.345245       100
11  social  water and sanitation  safe_Water  2011  99.477448       100
12  social  water and sanitation  safe_Water  2012  99.609673       100
13  social  water and sanitation  safe_Water  2013  99.671906       100
14  social  water and sanitation  safe_Water  2014  99.677628       100
15  social  water and sanitation  safe_Water  2015  99.683350       100
16  social  water and sanitation  safe_Water  2016  99.679100       100
17  social  water and sanitation  safe_Water  2017  99.674850       100
18  social  water and sanitation  safe_Water  2018  99.670601       100
19  social  water and sanitation  safe_Water  2019  99.666344       100
20  social  water and sanitation  safe_Water  2020  99.662094       100
21  social  water and sanitation  safe_Water  2021  99.657845       100
22  social  water and sanitation  safe_Water  2022  99.653595       100
23  social  water and sanitation  safe_Water  2023  99.649345       100
24  social  water and sanitation  safe_Water  2024  99.645096       100

In [23]:
safe_water[final_col_list].to_csv(input_path +  "/social/clean/access_safe_water_clean.csv",
                                  index = False)

### Safe Sanitation

In a similar manner to access to safe water, access to safe sanitation is also essential to a good quality of life i.e. safe sanitation facilities such as flushing toilets, sewers or sceptic tanks etc. 

Access to safe sanitation relates to SDG 6.2.1.

Source: https://unstats.un.org/sdgs/dataportal/database

The foundation for access safe sanitation is 100%.

In [24]:
safe_sanitation = pd.read_csv(input_path + "social/5_water_sanitation/safe_sanitation.csv")

safe_sanitation['Date'] = safe_sanitation['Year']
safe_sanitation['domain'] = "social"
safe_sanitation['dimension'] = "water and sanitation"
safe_sanitation['indicator'] = "safe_sanitation"
safe_sanitation['value'] = safe_sanitation['safe_sanitation'].astype(float)
safe_sanitation['boundary'] = 100

safe_sanitation[final_col_list]

    domain             dimension        indicator  Date      value  boundary
0   social  water and sanitation  safe_sanitation  2000  93.730186       100
1   social  water and sanitation  safe_sanitation  2001  93.815331       100
2   social  water and sanitation  safe_sanitation  2002  93.900467       100
3   social  water and sanitation  safe_sanitation  2003  93.985611       100
4   social  water and sanitation  safe_sanitation  2004  94.070747       100
5   social  water and sanitation  safe_sanitation  2005  94.155891       100
6   social  water and sanitation  safe_sanitation  2006  94.241028       100
7   social  water and sanitation  safe_sanitation  2007  94.326172       100
8   social  water and sanitation  safe_sanitation  2008  94.411308       100
9   social  water and sanitation  safe_sanitation  2009  94.496452       100
10  social  water and sanitation  safe_sanitation  2010  94.581589       100
11  social  water and sanitation  safe_sanitation  2011  94.666725       100
12  social  water and sanitation  safe_sanitation  2012  94.751869       100
13  social  water and sanitation  safe_sanitation  2013  94.837006       100
14  social  water and sanitation  safe_sanitation  2014  94.922150       100
15  social  water and sanitation  safe_sanitation  2015  95.007286       100
16  social  water and sanitation  safe_sanitation  2016  95.092430       100
17  social  water and sanitation  safe_sanitation  2017  95.177567       100
18  social  water and sanitation  safe_sanitation  2018  95.262711       100
19  social  water and sanitation  safe_sanitation  2019  95.348022       100
20  social  water and sanitation  safe_sanitation  2020  95.433136       100
21  social  water and sanitation  safe_sanitation  2021  95.518074       100
22  social  water and sanitation  safe_sanitation  2022  95.603012       100
23  social  water and sanitation  safe_sanitation  2023  95.687958       100
24  social  water and sanitation  safe_sanitation  2024  95.772896       100

In [25]:
safe_sanitation[final_col_list].to_csv(input_path +  "/social/clean/access_safe_sanitation_clean.csv", 
                                       index = False)

## Energy

### Population lacking access to electricity

Access to electricity has so many positive externalities on peoples life that access to it is essential to a good quality of life. Access to electricity relates to SDG 7.1.1.

Source: https://unstats.un.org/sdgs/dataportal/database

The foundation for access to energy is 100%.

In [26]:
access_elec = pd.read_csv(input_path + "social/6_energy/elec_access.csv")

access_elec['Date'] = access_elec['Year']
access_elec['domain'] = "social"
access_elec['dimension'] = "energy"
access_elec['indicator'] = "prop_access_electricity"
access_elec['value'] = access_elec['Prop_access_elec'].astype(float)
access_elec['boundary'] = 100

access_elec[final_col_list]

    domain dimension                indicator  Date  value  boundary
0   social    energy  prop_access_electricity  2000  100.0       100
1   social    energy  prop_access_electricity  2001  100.0       100
2   social    energy  prop_access_electricity  2002  100.0       100
3   social    energy  prop_access_electricity  2003  100.0       100
4   social    energy  prop_access_electricity  2004  100.0       100
5   social    energy  prop_access_electricity  2005  100.0       100
6   social    energy  prop_access_electricity  2006  100.0       100
7   social    energy  prop_access_electricity  2007  100.0       100
8   social    energy  prop_access_electricity  2008  100.0       100
9   social    energy  prop_access_electricity  2009  100.0       100
10  social    energy  prop_access_electricity  2010  100.0       100
11  social    energy  prop_access_electricity  2011  100.0       100
12  social    energy  prop_access_electricity  2012  100.0       100
13  social    energy  prop_access_electricity  2013  100.0       100
14  social    energy  prop_access_electricity  2014  100.0       100
15  social    energy  prop_access_electricity  2015  100.0       100
16  social    energy  prop_access_electricity  2016  100.0       100
17  social    energy  prop_access_electricity  2017  100.0       100
18  social    energy  prop_access_electricity  2018  100.0       100
19  social    energy  prop_access_electricity  2019  100.0       100
20  social    energy  prop_access_electricity  2020  100.0       100
21  social    energy  prop_access_electricity  2021  100.0       100
22  social    energy  prop_access_electricity  2022  100.0       100
23  social    energy  prop_access_electricity  2023  100.0       100
24  social    energy  prop_access_electricity  2024  100.0       100

In [27]:
access_elec[final_col_list].to_csv(input_path +  "/social/clean/access_energy_clean.csv", 
                                   index = False)

### Clean Fuel & Energy for cooking, heating and lighting 

Similarly with access to energy, access to clean fuels and technologies for cooking, heating, and lighting is essential to a good quality of life. Using dirty fuels for essential activities indoors can lead to serious and compounding health complications. Access to clean fuels relates to SDG 7.1.2.

Source: https://unstats.un.org/sdgs/dataportal/database

The foundation for access to clean fuels is 100%.

In [28]:
clean_fuel = pd.read_csv(input_path + "social/6_energy/clean_fuel_energy_cook_clean_light.csv")

clean_fuel['Date'] = clean_fuel['Year']
clean_fuel['domain'] = "social"
clean_fuel['dimension'] = "energy"
clean_fuel['indicator'] = "prop_access_fuel_cook_clean_light"
clean_fuel['value'] = clean_fuel['Prop_pop_reliance_clean_fuels_technology_cook_clean_light'].astype(float)
clean_fuel['boundary'] = 100

clean_fuel[final_col_list]

    domain dimension                          indicator  Date  value  boundary
0   social    energy  prop_access_fuel_cook_clean_light  2000   98.0       100
1   social    energy  prop_access_fuel_cook_clean_light  2001   99.0       100
2   social    energy  prop_access_fuel_cook_clean_light  2002   99.0       100
3   social    energy  prop_access_fuel_cook_clean_light  2003   99.0       100
4   social    energy  prop_access_fuel_cook_clean_light  2004   99.0       100
5   social    energy  prop_access_fuel_cook_clean_light  2005   99.0       100
6   social    energy  prop_access_fuel_cook_clean_light  2006   99.0       100
7   social    energy  prop_access_fuel_cook_clean_light  2007   99.0       100
8   social    energy  prop_access_fuel_cook_clean_light  2008   99.0       100
9   social    energy  prop_access_fuel_cook_clean_light  2009   99.0       100
10  social    energy  prop_access_fuel_cook_clean_light  2010   99.0       100
11  social    energy  prop_access_fuel_cook_clean_light  2011   99.0       100
12  social    energy  prop_access_fuel_cook_clean_light  2012   99.0       100
13  social    energy  prop_access_fuel_cook_clean_light  2013   99.0       100
14  social    energy  prop_access_fuel_cook_clean_light  2014   99.0       100
15  social    energy  prop_access_fuel_cook_clean_light  2015  100.0       100
16  social    energy  prop_access_fuel_cook_clean_light  2016  100.0       100
17  social    energy  prop_access_fuel_cook_clean_light  2017  100.0       100
18  social    energy  prop_access_fuel_cook_clean_light  2018  100.0       100
19  social    energy  prop_access_fuel_cook_clean_light  2019  100.0       100
20  social    energy  prop_access_fuel_cook_clean_light  2020  100.0       100
21  social    energy  prop_access_fuel_cook_clean_light  2021  100.0       100
22  social    energy  prop_access_fuel_cook_clean_light  2022  100.0       100
23  social    energy  prop_access_fuel_cook_clean_light  2023  100.0       100
24  social    energy  prop_access_fuel_cook_clean_light  2024  100.0       100

In [29]:
clean_fuel[final_col_list].to_csv(input_path +  "/social/clean/access_fuel_clean.csv", index = False)

## Conectivity

### Public Transport in Urban Areas (SDG 11.2.1)

The ability to move throughout a city is an key driver of connectivity. A key aspect of connectivity is public transportation and relates to SDG 11.2.1. This SDG measures the proportion of the Urban population lacking convenient access to public transport.

Access to public transport is defined as living within 500m of a low-capacity option such as a bus, or 1000m of a high capacity option such as a metro or train.  

Source: https://unstats.un.org/sdgs/dataportal/database

The foundation for access to public transport is 100%. 

This data will be ineterpolated before final analysis. Given the very few datapoints for this measure, it is unwise to rely to infer any generalisable conclusions from this data.

In [30]:
pub_transport = pd.read_csv(input_path + "social/7_conectivity/public_transport.csv")

pub_transport['Date'] = pub_transport['Year']
pub_transport['domain'] = "social"
pub_transport['dimension'] = "conectivity"
pub_transport['indicator'] = "public_transport_access"
pub_transport['value'] = pub_transport['Pro_pop_convenient_access_pub_transprt'].astype(float)
pub_transport['boundary'] = 100

pub_transport[final_col_list]

   domain    dimension                indicator  Date      value  boundary
0  social  conectivity  public_transport_access  2020  84.440909       100
1  social  conectivity  public_transport_access  2025  88.950000       100

In [31]:
pub_transport[final_col_list].to_csv(input_path +  "/social/clean/access_public_transport_clean.csv", 
                                     index = False)

### Internet Access (SDG 17.8.1)

Access to the internet in the modern world is essential to a good quality of life. Infact, in the modern world it is basically essential for people to access key services and the labour market to use the internet. Therefore, access to the internet relates to the SDG 17.8.1. 

The data tracks the proportion of the Australian population with no access to the Internet.

Source: https://unstats.un.org/sdgs/dataportal/database

The foundation for access to the internet is 100%.

In [32]:
internet_access = pd.read_csv(input_path + "social/7_conectivity/internet_usage.csv")
internet_access['Date'] = internet_access['Year']
internet_access['domain'] = "social"
internet_access['dimension'] = "conectivity"
internet_access['indicator'] = "prop_access_to_internet"
internet_access['value'] = internet_access['prop_internet_usage'].astype(float)
internet_access['boundary'] = 100

internet_access[final_col_list]

    domain    dimension                indicator  Date  value  boundary
0   social  conectivity  prop_access_to_internet  2000   46.8       100
1   social  conectivity  prop_access_to_internet  2001   52.7       100
2   social  conectivity  prop_access_to_internet  2005   63.0       100
3   social  conectivity  prop_access_to_internet  2006   66.0       100
4   social  conectivity  prop_access_to_internet  2007   69.5       100
5   social  conectivity  prop_access_to_internet  2008   71.7       100
6   social  conectivity  prop_access_to_internet  2009   74.3       100
7   social  conectivity  prop_access_to_internet  2010   76.0       100
8   social  conectivity  prop_access_to_internet  2011   79.5       100
9   social  conectivity  prop_access_to_internet  2012   79.0       100
10  social  conectivity  prop_access_to_internet  2013   83.5       100
11  social  conectivity  prop_access_to_internet  2014   84.0       100
12  social  conectivity  prop_access_to_internet  2015   84.6       100
13  social  conectivity  prop_access_to_internet  2016   86.5       100
14  social  conectivity  prop_access_to_internet  2017   86.5       100
15  social  conectivity  prop_access_to_internet  2018   90.0       100
16  social  conectivity  prop_access_to_internet  2019   93.6       100
17  social  conectivity  prop_access_to_internet  2020   94.7       100
18  social  conectivity  prop_access_to_internet  2021   97.0       100
19  social  conectivity  prop_access_to_internet  2022   96.1       100
20  social  conectivity  prop_access_to_internet  2023   96.1       100
21  social  conectivity  prop_access_to_internet  2024   96.1       100

In [33]:
internet_access[final_col_list].to_csv(input_path +  "/social/clean/access_internet_clean.csv",
                                       index = False)

## Housing 

Adequate housing is essential to a good quality of life. The housing measure adopting in the study was the proportion of the urban population living in slums or informal settlements (relating to SDG 11.1.1).

Source: https://unstats.un.org/sdgs/dataportal/database

Whilst there are still people living in slums in Aus, it is not an entirely appropriate measure for adequate housing in the Australian context.

In [34]:
housing_df = pd.read_csv(input_path + "social/8_housing/housing.csv")
housing_df['Date'] = housing_df['Year']
housing_df['domain'] = "social"
housing_df['dimension'] = "housing"
housing_df['indicator'] = "prop_living_in_slums"
housing_df['value'] = housing_df['Prop_urban_pop_living_slums'].astype(float)

housing_df

,Year,Prop_urban_pop_living_slums,Date,domain,dimension,indicator,value
0,2000,0.17,2000,social,housing,prop_living_in_slums,0.17
1,2002,0.17,2002,social,housing,prop_living_in_slums,0.17
2,2004,0.15,2004,social,housing,prop_living_in_slums,0.15
3,2006,0.13,2006,social,housing,prop_living_in_slums,0.13
4,2008,0.11,2008,social,housing,prop_living_in_slums,0.11
5,2010,0.09,2010,social,housing,prop_living_in_slums,0.09
6,2012,0.07,2012,social,housing,prop_living_in_slums,0.07
7,2014,0.05,2014,social,housing,prop_living_in_slums,0.05
8,2016,0.04,2016,social,housing,prop_living_in_slums,0.04
9,2018,0.04,2018,social,housing,prop_living_in_slums,0.04
10,2020,0.04,2020,social,housing,prop_living_in_slums,0.04
11,2022,0.04,2022,social,housing,prop_living_in_slums,0.04
12,2024,0.04,2024,social,housing,prop_living_in_slums,0.04

### Social Housing Wait List

Therefore, I choose to adopt a measure of how many people in the greatest need are on waiting lists for social housing. 

According to the Australian Institute of Health and Wellbeing; *"In all states and territories, access to social housing is managed through the use of waiting lists with priority given to those considered to be high priority applicants".*

Therefore, I have defined a measure of the percentage of people on the waiting list in the "greatest need" *(defined slightly differently across each state/territory)*, as a proportion of all people on the waitlist. 

Source: https://www.aihw.gov.au/reports/housing-assistance/housing-assistance-in-australia-2023/contents/households-and-waiting-lists

The social foundation for this should be zero i.e. everyone in the greatest need for housing gets acccess to social housing. 

This is an incomplete measure, but there is available data and hence I have adopted it over the proportion of people living in slums. I will extrapolate this data to 2024 before final analysis.

In [35]:
wait_list_df = pd.read_csv(input_path + "social/8_housing/social_housing_waiting_list.csv")
wait_list_df.head()

wait_list_df['Date'] = wait_list_df['Year']
wait_list_df['domain'] = "social"
wait_list_df['dimension'] = "housing"
wait_list_df['indicator'] = "prop_in_need_on_waiting_list"
wait_list_df['value'] = wait_list_df['prop_in_greatest_need'].astype(float) * 100
wait_list_df['boundary'] = 0

wait_list_df[final_col_list]

   domain dimension                     indicator  Date  value  boundary
0  social   housing  prop_in_need_on_waiting_list  2014   28.0         0
1  social   housing  prop_in_need_on_waiting_list  2015   25.7         0
2  social   housing  prop_in_need_on_waiting_list  2016   25.6         0
3  social   housing  prop_in_need_on_waiting_list  2017   26.7         0
4  social   housing  prop_in_need_on_waiting_list  2018   32.6         0
5  social   housing  prop_in_need_on_waiting_list  2019   35.4         0
6  social   housing  prop_in_need_on_waiting_list  2020   37.7         0
7  social   housing  prop_in_need_on_waiting_list  2021   41.4         0
8  social   housing  prop_in_need_on_waiting_list  2022   38.9         0

In [36]:
wait_list_df[final_col_list].to_csv(input_path +  "/social/clean/wait_list_clean.csv", index = False)

## Equality

### Gender

Gender equality *(dare I say gender liberation)* is essential to a good quality of life for everyone (no matter their gender). This relates to the goal of SDG 5. The original paper has adopted the Gender Inequality Index with measures the gap between men and women in terms of reproductive healh, empowerment and employment. UNDP outlines the GII as: 

*"The GII measures gender inequalities in three key dimensions – reproductive health, empowerment, and labour market. Reproductive health is measured by maternal mortality ratio and adolescent birth rates; empowerment is measured by the shares of parliamentary seats held and population with at least some secondary education by each gender; and labour market participation is measured by the labour force participation rates for women and men."*

Source:https://hdr.undp.org/data-center/specific-country-data#/countries/AUS

The social foundation for the GII is zero. Despite sincere attempts by this indicator to include multiple dimensions, it is still an inadequate measure in describing other outcomes of gendered oppression. Perhaps most noteably it does not account for the caring and reproductive labour that is disproportionally completed by Women. Seeking to expand this measure to include other dimensions of gender equality is an essential next step in the quantification of any doughnut.

In [37]:
gender_df = pd.read_csv(input_path + "social/9_equality/HDI_data_aus.csv")
gender_df = gender_df[gender_df['key'].str.contains("Gender Inequality Index")].reset_index(drop = True)
gender_df['Date'] = np.arange(1990,2024,1)
gender_df['domain'] = "social"
gender_df['dimension'] = "equality"
gender_df['indicator'] = "gender_inequality_index"
gender_df['value'] = gender_df['value'].astype(float)
gender_df['boundary'] = 0

gender_df[final_col_list]

    domain dimension                indicator  Date  value  boundary
0   social  equality  gender_inequality_index  1990  0.188         0
1   social  equality  gender_inequality_index  1991  0.187         0
2   social  equality  gender_inequality_index  1992  0.187         0
3   social  equality  gender_inequality_index  1993  0.183         0
4   social  equality  gender_inequality_index  1994  0.181         0
5   social  equality  gender_inequality_index  1995  0.178         0
6   social  equality  gender_inequality_index  1996  0.177         0
7   social  equality  gender_inequality_index  1997  0.174         0
8   social  equality  gender_inequality_index  1998  0.171         0
9   social  equality  gender_inequality_index  1999  0.158         0
10  social  equality  gender_inequality_index  2000  0.153         0
11  social  equality  gender_inequality_index  2001  0.152         0
12  social  equality  gender_inequality_index  2002  0.146         0
13  social  equality  gender_inequality_index  2003  0.141         0
14  social  equality  gender_inequality_index  2004  0.137         0
15  social  equality  gender_inequality_index  2005  0.137         0
16  social  equality  gender_inequality_index  2006  0.135         0
17  social  equality  gender_inequality_index  2007  0.136         0
18  social  equality  gender_inequality_index  2008  0.140         0
19  social  equality  gender_inequality_index  2009  0.137         0
20  social  equality  gender_inequality_index  2010  0.137         0
21  social  equality  gender_inequality_index  2011  0.132         0
22  social  equality  gender_inequality_index  2012  0.131         0
23  social  equality  gender_inequality_index  2013  0.122         0
24  social  equality  gender_inequality_index  2014  0.116         0
25  social  equality  gender_inequality_index  2015  0.109         0
26  social  equality  gender_inequality_index  2016  0.101         0
27  social  equality  gender_inequality_index  2017  0.094         0
28  social  equality  gender_inequality_index  2018  0.091         0
29  social  equality  gender_inequality_index  2019  0.079         0
30  social  equality  gender_inequality_index  2020  0.072         0
31  social  equality  gender_inequality_index  2021  0.065         0
32  social  equality  gender_inequality_index  2022  0.056         0
33  social  equality  gender_inequality_index  2023  0.056         0

In [38]:
gender_df[gender_df['Date']>1999][final_col_list].to_csv(input_path +  "/social/clean/GII_clean.csv", index = False)

### No Difference in Imprisonment Rates between Indigenous and Non-Indigenous Australians

There was no measure included for racial equality in the doughnut study. In Australia there is a unconscionably high gap in imprisonment rates between Indigenous and Non-indigenous Australians. 

Source: https://www.pc.gov.au/closing-the-gap-data/dashboard/outcome-area/criminal-justice/

Eventually we push for no prisons, however more immediately, the gap between indigenous and non-indigenous people in prisons per 100,000 people should be zero by 2030. This seems like the most obvious racial equality index to measure for a doughnut in Australia.

I calculate the percentage difference between the imprissonment rate per 100,000 people using the productivity comissions data as such:

$$ \Delta_{\text{Imprisonment Rate}}\% = \frac{\text{Indigenous Prisoners per 100000}_t - \text{Non-indigenous Prisoners per 100000}_t}{\text{Non-indigenous Prisoners per 100000}_t}$$

That is for their to be equality in imprisonment rates, $ \Delta_{\text{Imprisonment Rate}}\% = 0$. Therefore, the social foundation is set at zero. To create a ratio, bounded by 0 and 1, a worst case scenario will be adopted. This is further described in the analysis script. 

This is obviously an insufficient measure for true racial equality. More needs to be added to the social foundation to improve this aspect of the doughnut.

In [39]:
imprisonment = pd.read_csv(input_path + "social/9_equality/imprisonment_rates.csv")
imprisonment = imprisonment[(imprisonment['Description1'] == 'Age-standardised imprisonment rate per 100000 adults at 30 June') &
                           (imprisonment['Description7'] == "Actual")][['Year', 'Indigenous_Status', 'Aust']]

imprisonment['Aust'] = imprisonment['Aust'].astype(float)
wide_imprison = pd.pivot_table(imprisonment, 
                               columns = ['Indigenous_Status'], 
                               index = ['Year'], 
                               values = "Aust").reset_index()
wide_imprison

Indigenous_Status,Year,Aboriginal and Torres Strait Islander people,Non-Indigenous people
0,2016,1730.2,163.0
1,2017,1824.5,170.0
2,2018,1887.4,174.4
3,2019,1925.4,172.2
4,2020,1880.5,159.5
5,2021,2004.6,165.3
6,2022,1943.6,151.2
7,2023,2049.6,149.5
8,2024,2318.4,146.4
9,2025,2500.2,149.1

In [40]:
imprisonment = pd.read_csv(input_path + "social/9_equality/imprisonment_rates.csv")
imprisonment = imprisonment[(imprisonment['Description1'] == 'Age-standardised imprisonment rate per 100000 adults at 30 June') &
                           (imprisonment['Description7'] == "Actual")][['Year', 'Indigenous_Status', 'Aust']]

imprisonment['Aust'] = imprisonment['Aust'].astype(float)
wide_imprison = pd.pivot_table(imprisonment, 
                               columns = ['Indigenous_Status'], 
                               index = ['Year'], 
                               values = "Aust").reset_index()

wide_imprison['imprison_gap_per_100000'] = wide_imprison['Aboriginal and Torres Strait Islander people'] - wide_imprison['Non-Indigenous people']
wide_imprison['perc_imprison_gap_per_100000'] = wide_imprison['imprison_gap_per_100000']/wide_imprison['Non-Indigenous people']
wide_imprison['Date'] = wide_imprison['Year']
wide_imprison['domain'] = "social"
wide_imprison['dimension'] = "equality"
wide_imprison['indicator'] = "perc_more_ind_prison_compared_to_non_ind_prisons_per_100000"
wide_imprison['value'] = wide_imprison['perc_imprison_gap_per_100000'].astype(float)
wide_imprison['boundary'] = 0
wide_imprison['ratio'] = (wide_imprison['value'] - 1)/wide_imprison['value']

wide_imprison[final_col_list + ['ratio']]

Indigenous_Status,domain,dimension,indicator,Date,value,boundary,ratio
0,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2016,9.614724,0,0.895993
1,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2017,9.732353,0,0.897250
2,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2018,9.822248,0,0.898190
3,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2019,10.181185,0,0.901780
4,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2020,10.789969,0,0.907321
5,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2021,11.127042,0,0.910129
6,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2022,11.854497,0,0.915644
7,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2023,12.709699,0,0.921320
8,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2024,14.836066,0,0.932597
9,social,equality,perc_more_ind_prison_compared_to_non_ind_priso...,2025,15.768612,0,0.936583

In [41]:
wide_imprison[final_col_list].to_csv(input_path +  "/social/clean/imprison_rates_clean.csv", index = False)

## Social Cohesion

An unfortunate name for this social foundation given it's context in [AusPol](https://open.substack.com/pub/deepcutnews/p/why-social-cohesion-is-a-dangerous?r=64iy37&utm_campaign=post&utm_medium=web). The basic idea of it is probably more related to a true sense of belonging and community *(of which there are many recoreded benefits)*. 

### Social Support
The first indicator adopted was around social support. Specifically those that lack social support, or the proportion of the population stating that they are without someone to count on in times of trouble.

Source: https://data-explorer.oecd.org/

The social foundation for this measure is set to zero i.e. no lack of social support.

In [42]:
social_support = pd.read_csv(input_path + "social/10_social_cohesion/lack_social_support.csv")

social_support['Date'] = social_support['TIME_PERIOD']
social_support['domain'] = "social"
social_support['dimension'] = "social cohesion"
social_support['indicator'] = "lack_social_support"
social_support['value'] = social_support['OBS_VALUE'].astype(float)
social_support['boundary'] = 0

social_support[final_col_list].sort_values("Date").reset_index(drop=True)

    domain        dimension            indicator  Date      value  boundary
0   social  social cohesion  lack_social_support  2006   3.324733         0
1   social  social cohesion  lack_social_support  2007   3.324733         0
2   social  social cohesion  lack_social_support  2008   4.926543         0
3   social  social cohesion  lack_social_support  2009   4.926543         0
4   social  social cohesion  lack_social_support  2010   4.926543         0
5   social  social cohesion  lack_social_support  2011   5.324185         0
6   social  social cohesion  lack_social_support  2012   5.324185         0
7   social  social cohesion  lack_social_support  2013   5.324185         0
8   social  social cohesion  lack_social_support  2014   6.041596         0
9   social  social cohesion  lack_social_support  2015   6.041596         0
10  social  social cohesion  lack_social_support  2016   6.041596         0
11  social  social cohesion  lack_social_support  2017   5.550078         0
12  social  social cohesion  lack_social_support  2018   5.550078         0
13  social  social cohesion  lack_social_support  2019   5.550078         0
14  social  social cohesion  lack_social_support  2020   6.713678         0
15  social  social cohesion  lack_social_support  2021   6.713678         0
16  social  social cohesion  lack_social_support  2022   6.713678         0
17  social  social cohesion  lack_social_support  2023  10.043193         0
18  social  social cohesion  lack_social_support  2024  10.043193         0
19  social  social cohesion  lack_social_support  2025  10.043193         0

In [43]:
social_support[final_col_list].sort_values("Date").reset_index(drop=True).to_csv(input_path +  "/social/clean/lack_social_support_clean.csv", 
                                                                                 index = False)

### Palma Ratio

Another key aspect of social cohesion is income equality. The paper adopted the Palma ratio which compares the income share of the richest 10% of people relative to the poorest 40% in Australia.

The data was sourced from our world in data: ["Palma ratio (before tax)"](https://ourworldindata.org/grapher/palma-ratio-wid?tab=line&country=~AUS&mapSelect=~AUS&v=1&csvType=filtered&useColumnShortNames=false&welfare_type=before_tax).

The paper adopted this social foundation to be a Palma ratio of 2 i.e. the top 10% of income earners makes double the income of the bottom 40% of income earners. This is another crude and incomplete measure, but it does a better job at capturing the income inequalities than the Gini Coefficient. The choice of 2 also appears to be arbitrary and more suited to a measure of the proportion of the global that lives in a country with the Palma ratio greater than two. However, given a lack of other alternatives, this boundary and indicator was adopted.

In [44]:
ineq_df = pd.read_csv(input_path + "social/10_social_cohesion/palma_ratio_before_tax.csv")
ineq_df = ineq_df[ineq_df['Year'] > 2000]

ineq_df['Date'] = ineq_df['Year']
ineq_df['domain'] = "social"
ineq_df['dimension'] = "social cohesion"
ineq_df['indicator'] = "palma_ratio"
ineq_df['value'] = ineq_df['Palma ratio (before tax)'].astype(float)
ineq_df['boundary'] = 2

ineq_df[final_col_list]

    domain        dimension    indicator  Date     value  boundary
54  social  social cohesion  palma_ratio  2001  2.774278         2
55  social  social cohesion  palma_ratio  2002  3.093839         2
56  social  social cohesion  palma_ratio  2003  2.935194         2
57  social  social cohesion  palma_ratio  2004  2.996400         2
58  social  social cohesion  palma_ratio  2005  3.163380         2
59  social  social cohesion  palma_ratio  2006  3.161682         2
60  social  social cohesion  palma_ratio  2007  3.092391         2
61  social  social cohesion  palma_ratio  2008  3.261407         2
62  social  social cohesion  palma_ratio  2009  3.201459         2
63  social  social cohesion  palma_ratio  2010  3.187386         2
64  social  social cohesion  palma_ratio  2011  3.180995         2
65  social  social cohesion  palma_ratio  2012  3.206581         2
66  social  social cohesion  palma_ratio  2013  3.239070         2
67  social  social cohesion  palma_ratio  2014  3.224792         2
68  social  social cohesion  palma_ratio  2015  3.268246         2
69  social  social cohesion  palma_ratio  2016  3.171053         2
70  social  social cohesion  palma_ratio  2017  3.250710         2
71  social  social cohesion  palma_ratio  2018  3.097248         2
72  social  social cohesion  palma_ratio  2019  3.143266         2
73  social  social cohesion  palma_ratio  2020  3.113346         2
74  social  social cohesion  palma_ratio  2021  3.293953         2
75  social  social cohesion  palma_ratio  2022  3.327342         2

In [45]:
ineq_df[final_col_list].to_csv(input_path +  "/social/clean/palma_clean.csv", index = False)

## Political Voice

Political voice is a key aim of SDG 16.7. The paper adopted a V-DEM measure that doesn't really work very well for a single country measure. 

Given Australia's compulsory voting system, below 100% turnout either relates to missing the election for a miscellaneous reason, or feelings in disenfranchisement making a donkey vote an attractive alternative. It is hard to know for sure and voter turnout has been generall high in Australia *(if not falling very slightly from ~94\% to 90\% in more recent elections)*.

Source: https://data-explorer.oecd.org/

In [46]:
vote = pd.read_csv(input_path + "social/11_political_voice/voter_turnout.csv")
vote = vote[vote['Measure'] == "Voter turnout"]
vote['Date'] = vote['TIME_PERIOD']
vote['domain'] = "social"
vote['dimension'] = "political voice"
vote['indicator'] = "voter_turnout"
vote['value'] = vote['OBS_VALUE'].astype(float)

vote.sort_values("Date").reset_index(drop=True)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,MEASURE,Measure,UNIT_MEASURE,Unit of measure,...,Unit multiplier,DECIMALS,Decimals,BASE_PER,Base period,Date,domain,dimension,indicator,value
0,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2004,social,political voice,voter_turnout,94.32
1,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2007,social,political voice,voter_turnout,94.76
2,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2010,social,political voice,voter_turnout,93.22
3,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2013,social,political voice,voter_turnout,93.23
4,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2016,social,political voice,voter_turnout,91.01
5,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2019,social,political voice,voter_turnout,91.89
6,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2022,social,political voice,voter_turnout,89.74
7,DATAFLOW,OECD.WISE.WDP:DSD_HSL@DF_HSL_CWB(1.1),Current well-being,I,AUS,Australia,8_2,Voter turnout,PT_VOTES,Percentage of votes,...,Units,2,Two,_Z,NaN,2025,social,political voice,voter_turnout,90.67

It is hard to say if this is an increase in people believing they have no political voice or not. Therefore an alternative measure is preferable. 

### Not having a say in government

Using similar survery data from: https://data-explorer.oecd.org/,

We can pull out recent data on the percentage of population aged 16-65 years who report that they believe they have no say in government.

As we can see below this actually decreased in the 2023 election. This is probably a better measure than voter turnout given Aus's compulsory voting, even if it has significantly less observations. I will interpolate and extrapolate this data before conducting the final analysis.

In [47]:
govt = pd.read_csv(input_path + "social/11_political_voice/voter_turnout.csv")
govt = govt[govt['Measure'] == "Not having a say in government"]
govt['Date'] = govt['TIME_PERIOD']
govt['domain'] = "social"
govt['dimension'] = "political voice"
govt['indicator'] = "no_say_in_govt"
govt['value'] = govt['OBS_VALUE'].astype(float)
govt['boundary'] = 0

govt[final_col_list].sort_values("Date").reset_index(drop=True)

   domain        dimension       indicator  Date      value  boundary
0  social  political voice  no_say_in_govt  2021  46.815718         0
1  social  political voice  no_say_in_govt  2023  35.585077         0

In [48]:
govt[final_col_list].sort_values("Date").reset_index(drop=True).to_csv(input_path +  "/social/clean/no_say_govt_clean.csv", 
                                                                       index = False)

## Peace & Justice

### Homicide

SDG 16.1.1 relates to keeping the homicide rate of 5 or more per 100,000. The basic idea being this proxies for people not resorting to violence *(peace)* to resolve differences due to trust that institutions will support  accountability *(justice)*. Another crude measure that does not account for systemic violence and the states monopoly on violence, but it'll do for now.

Source: https://unstats.un.org/sdgs/dataportal/database

The social foundation for this is 5 homicides per 100,000 people.

In [49]:
homicide_df = pd.read_csv(input_path + "social/12_peace_justice/homicide.csv")
homicide_df.head()

homicide_df['Date'] = homicide_df['Year']
homicide_df['domain'] = "social"
homicide_df['dimension'] = "peace and justice"
homicide_df['indicator'] = "homicide_rate_100000"
homicide_df['value'] = homicide_df['Num_victims_intentional_homicide_per_100000'].astype(float)
homicide_df['boundary'] = 5

homicide_df[final_col_list]

    domain          dimension             indicator  Date  value  boundary
0   social  peace and justice  homicide_rate_100000  2000   1.89         5
1   social  peace and justice  homicide_rate_100000  2001   1.79         5
2   social  peace and justice  homicide_rate_100000  2002   1.87         5
3   social  peace and justice  homicide_rate_100000  2003   1.52         5
4   social  peace and justice  homicide_rate_100000  2004   1.31         5
5   social  peace and justice  homicide_rate_100000  2005   1.28         5
6   social  peace and justice  homicide_rate_100000  2006   1.36         5
7   social  peace and justice  homicide_rate_100000  2007   1.22         5
8   social  peace and justice  homicide_rate_100000  2008   1.22         5
9   social  peace and justice  homicide_rate_100000  2009   1.21         5
10  social  peace and justice  homicide_rate_100000  2010   1.04         5
11  social  peace and justice  homicide_rate_100000  2011   1.10         5
12  social  peace and justice  homicide_rate_100000  2012   1.06         5
13  social  peace and justice  homicide_rate_100000  2013   1.05         5
14  social  peace and justice  homicide_rate_100000  2014   1.03         5
15  social  peace and justice  homicide_rate_100000  2015   0.99         5
16  social  peace and justice  homicide_rate_100000  2016   0.93         5
17  social  peace and justice  homicide_rate_100000  2017   0.84         5
18  social  peace and justice  homicide_rate_100000  2018   0.88         5
19  social  peace and justice  homicide_rate_100000  2019   0.88         5
20  social  peace and justice  homicide_rate_100000  2020   0.86         5
21  social  peace and justice  homicide_rate_100000  2021   0.74         5
22  social  peace and justice  homicide_rate_100000  2022   0.84         5
23  social  peace and justice  homicide_rate_100000  2023   0.84         5
24  social  peace and justice  homicide_rate_100000  2024   0.94         5

In [50]:
homicide_df[final_col_list].to_csv(input_path +  "/social/clean/homicide_clean.csv", index = False)

# Ecological Indicators

There is necessarily some confusion around the ecological indicators being the "planetary boundaries" when we are talking about one country / landmass / continent. 

We can't simply adopt the [9 planetary boundaries](https://www.stockholmresilience.org/research/planetary-boundaries.html) directly, not because of a lack of data, but because the choice of boundary will be very different between countries. For example, does a "fair share" or a "cumulative usage" approach to defining a boundary apply? No doubt there will also need to be normative assertions required to support the choice. Indeed the paper even notes their adoption of proxy inidcators that do not form part of the planetary boundaries:

*"In addition, we include six per capita environmental footprint proxy indicators for our analysis of inequalities at the country-cluster scale, which are informed by planetary boundaries science, but are not directly comparable to the planetary boundaries."* (pg. 12)

Therefore, the data i've choosen has tried to best mimic the global data used in the doughnut v3 study. I will try to explain my choices as I go.

## Co2 emissions

Hopefully this one is self explanatory. Co2 is the most emitted greenhouse gas and is the key driver of increased global average temperature. Obviously PPM cannot be used because it doesn't account for where those Co2 emissions came from *(emissions don't care about borders)*. Therefore, I adopt the consumption of Co2 emissions per capita per year as the indicator. 

Data sources: Global Carbon Budget (2025) Population based on various sources (2024) – with major processing by Our World in Data

- co2: https://globalcarbonbudget.org/
- population (various sources): https://ourworldindata.org/population-sources

The ecological ceiling in that case is at most 0.95 t CO2 per capita per year.

In [51]:
co2 = pd.read_csv(input_path + "/ecological/1_climate_change/co2_emissions_per_capita.csv")

In [52]:
co2['domain'] = "ecological"
co2['dimension'] = "climate change"
co2['indicator'] = "co2_emissions_per_capita"
co2['value'] = co2['Co2_emissions_per_capita']
co2['Date'] = co2['Year']
co2['boundary'] = 0.95

co2[co2["Year"] > 2000][final_col_list]

,domain,dimension,indicator,Date,value,boundary
206,ecological,climate change,co2_emissions_per_capita,2001,18.469387,0.95
207,ecological,climate change,co2_emissions_per_capita,2002,18.495451,0.95
208,ecological,climate change,co2_emissions_per_capita,2003,18.708109,0.95
209,ecological,climate change,co2_emissions_per_capita,2004,19.055769,0.95
210,ecological,climate change,co2_emissions_per_capita,2005,18.974682,0.95
211,ecological,climate change,co2_emissions_per_capita,2006,19.007372,0.95
212,ecological,climate change,co2_emissions_per_capita,2007,19.036264,0.95
213,ecological,climate change,co2_emissions_per_capita,2008,18.917550,0.95
214,ecological,climate change,co2_emissions_per_capita,2009,18.683231,0.95
215,ecological,climate change,co2_emissions_per_capita,2010,18.292547,0.95
216,ecological,climate change,co2_emissions_per_capita,2011,17.966120,0.95
217,ecological,climate change,co2_emissions_per_capita,2012,17.722460,0.95
218,ecological,climate change,co2_emissions_per_capita,2013,17.121933,0.95
219,ecological,climate change,co2_emissions_per_capita,2014,16.639103,0.95
220,ecological,climate change,co2_emissions_per_capita,2015,16.727460,0.95
221,ecological,climate change,co2_emissions_per_capita,2016,16.837934,0.95
222,ecological,climate change,co2_emissions_per_capita,2017,16.716150,0.95
223,ecological,climate change,co2_emissions_per_capita,2018,16.512163,0.95
224,ecological,climate change,co2_emissions_per_capita,2019,16.282620,0.95
225,ecological,climate change,co2_emissions_per_capita,2020,15.481285,0.95
226,ecological,climate change,co2_emissions_per_capita,2021,14.966330,0.95
227,ecological,climate change,co2_emissions_per_capita,2022,14.658930,0.95
228,ecological,climate change,co2_emissions_per_capita,2023,14.529289,0.95
229,ecological,climate change,co2_emissions_per_capita,2024,14.477199,0.95

In [53]:
co2[co2["Year"] < 1850]['value'].mean()

np.float64(0.03237138181818182)

In [54]:
co2[co2["Year"] > 1850]['value'].mean()

np.float64(7.588483074712644)

In [55]:
co2[co2["Year"] > 2000][final_col_list].to_csv(input_path + "/ecological/clean/CO2_clean.csv", index = False)

## Ocean acidification

The oceans absorb most of the heat in the atmosphere, however this is increasing the acidity of the water. The v3 doughnut study adopted the average saturation state of aragonite at the ocean surface with a baseline figure of 3.44.

I sourced data from open access to ocean data which has an option from data collected off the east coast of Lutruwita / Tasmania. 

Source: https://portal.aodn.org.au/search?uuid=89b495cc-7382-43c0-abef-d1e66738a924 (accessed 2/8/26)

I am unsure what the pre-industrial saturation rate of aragonite is, but the paper has suggested that at least 80% of the pre industrial baseline is an appropriate boundary, hence I will adopt that.

In [56]:
acid = pd.read_csv(input_path + "ecological/2_ocean_acid/IMOS_-_National_Mooring_Network_-_Acidification_Moorings_(AM)_Sub-Facility_-_delayed_mode_data.csv",
                  skiprows = 20)

In [57]:
# create date
acid['date'] = pd.to_datetime(acid['TIME'])
acid['Year'] = pd.to_datetime(acid['TIME']).dt.year

In [58]:
acid_grouped = acid.groupby("Year")['OMEGA_A'].mean().dropna().reset_index()

In [59]:
# create columns
acid_grouped['domain'] = "ecological"
acid_grouped['dimension'] = "ocean acidification"
acid_grouped['indicator'] = "omega_a"
acid_grouped['value'] = acid_grouped['OMEGA_A']
acid_grouped['Date'] = acid_grouped['Year']
acid_grouped['boundary'] = 3.44*.8


acid_grouped[final_col_list]

        domain            dimension indicator  Date     value  boundary
0   ecological  ocean acidification   omega_a  2015  2.382900     2.752
1   ecological  ocean acidification   omega_a  2016  2.639750     2.752
2   ecological  ocean acidification   omega_a  2017  2.497939     2.752
3   ecological  ocean acidification   omega_a  2018  2.828270     2.752
4   ecological  ocean acidification   omega_a  2019  2.544030     2.752
5   ecological  ocean acidification   omega_a  2020  2.703830     2.752
6   ecological  ocean acidification   omega_a  2021  2.667797     2.752
7   ecological  ocean acidification   omega_a  2022  2.934990     2.752
8   ecological  ocean acidification   omega_a  2023  2.223330     2.752
9   ecological  ocean acidification   omega_a  2024  2.516188     2.752
10  ecological  ocean acidification   omega_a  2025  2.523889     2.752

In [60]:
acid_grouped[final_col_list][final_col_list].to_csv(input_path + "/ecological/clean/acid_clean.csv", 
                                                    index = False)

## Chemical pollution
### Material Footprint
I couldn't find direct chemical pollution data for Australia. But I could find information on material footprint per capita which I will use as a proxy for chemical pollution. It measures the per capita footproint for minerals, fossil fuels and biomass produced in Aus.

Source: https://www.resourcepanel.org/global-material-flows-database

In terms of a boundary, and earlier paper investigating ecological overshoots used population share of global emissions to calculate a boundary for this ecological measure using a "fair share" approach. It worked out to decrease at roughly 0.1 decrease in material footprint per year starting at 9.1. I will adopt this same approach and note that the ratio will simply be the `value / boundary`.

paper: https://static1.squarespace.com/static/59bc0e610abd04bd1e067ccc/t/619c9175f5f59b35d8f7a533/1637650817017/Fanning+et+al_2021+-+The+social+shortfall+and+ecological+overshoot+of+nations.pdf

In [61]:
material_footprint = pd.read_csv(input_path + "/ecological/2_chem_pollution/material_footprint_per_capita.csv")
material_footprint = material_footprint[['1970', '1971',
       '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980',
       '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989',
       '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998',
       '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']].T.reset_index().rename(columns = {"index" : "Year", 0 : "Material Footprint (RMC) per capita"})

# fitler for > 1995

material_footprint = material_footprint[material_footprint['Year'].astype(int) >= 1992]
material_footprint['domain'] = "ecological"
material_footprint['dimension'] = "Material Footprint"
material_footprint['indicator'] = "material_footprint"
material_footprint['value'] = material_footprint['Material Footprint (RMC) per capita']
material_footprint['Date'] = material_footprint['Year'].astype(int)
material_footprint['boundary'] = np.arange(9.1, 5.8, -0.1)

material_footprint[material_footprint['Date'] > 1999][final_col_list]

,domain,dimension,indicator,Date,value,boundary
30,ecological,Material Footprint,material_footprint,2000,33.2517,8.3
31,ecological,Material Footprint,material_footprint,2001,34.5897,8.2
32,ecological,Material Footprint,material_footprint,2002,34.9966,8.1
33,ecological,Material Footprint,material_footprint,2003,38.2272,8.0
34,ecological,Material Footprint,material_footprint,2004,40.5506,7.9
35,ecological,Material Footprint,material_footprint,2005,41.7304,7.8
36,ecological,Material Footprint,material_footprint,2006,41.6703,7.7
37,ecological,Material Footprint,material_footprint,2007,42.2755,7.6
38,ecological,Material Footprint,material_footprint,2008,35.6241,7.5
39,ecological,Material Footprint,material_footprint,2009,36.4525,7.4
40,ecological,Material Footprint,material_footprint,2010,37.6499,7.3
41,ecological,Material Footprint,material_footprint,2011,36.9646,7.2
42,ecological,Material Footprint,material_footprint,2012,36.1518,7.1
43,ecological,Material Footprint,material_footprint,2013,34.0362,7.0
44,ecological,Material Footprint,material_footprint,2014,34.1449,6.9
45,ecological,Material Footprint,material_footprint,2015,32.2598,6.8
46,ecological,Material Footprint,material_footprint,2016,31.9522,6.7
47,ecological,Material Footprint,material_footprint,2017,34.0499,6.6
48,ecological,Material Footprint,material_footprint,2018,33.3585,6.5
49,ecological,Material Footprint,material_footprint,2019,33.2981,6.4
50,ecological,Material Footprint,material_footprint,2020,31.2669,6.3
51,ecological,Material Footprint,material_footprint,2021,31.9297,6.2
52,ecological,Material Footprint,material_footprint,2022,31.6493,6.1
53,ecological,Material Footprint,material_footprint,2023,31.4649,6.0
54,ecological,Material Footprint,material_footprint,2024,31.1222,5.9

In [62]:
material_footprint[material_footprint['Date'] > 1999][final_col_list].to_csv(input_path + "/ecological/clean/material_footprint_clean.csv", 
                                                    index = False)

## Nutrient Pollution

Phosphorus and Nitrogen footprint used in agriculture can cause serious environmental impacts to waters and aquatic life. Unfortunately, I couldn't find comprehensive and disaggregated data on Phosphorus and Nitrogen consumption in Aus. I could find data on fertiliser consumption and so have tried to recreate a per capita usage using the following datasets:
- fertiliser consumption: https://ourworldindata.org/grapher/fertilizer-total-use?country=~AUS
    
    - Data sources: Food and Agriculture Organization of the United Nations (2025) Food and Agriculture Organization of the United Nations (2025) – with major processing by Our World in Data
- Population: https://ourworldindata.org/explorers/population-and-demography?time=1950..2023&country=~AUS&indicator=Population&Sex=Both+sexes&Age=Total&Projection+scenario=None
    
    - UN, World Population Prospects (2024) – processed by Our World in Data

The boundary for the paper is split by Phosphorus and Nitrogen with the baseline being zero for both. Because nitrogen is much more ubiquitous than Phosphorus I am going to adopt the boundary of 8.5kg of nitrogen per capita per year as my boundary, acknowledging that this is insufficient and needs a more robust boundary.

In [63]:
fert = pd.read_csv(input_path + "/ecological/3_nutrient_pollution/per_capita_fertilizer_use.csv")

fert['domain'] = "ecological"
fert['dimension'] = "Nutrient Pollution"
fert['indicator'] = "fertilizer_cons_kg_per_capita"
fert['value'] = fert['fert_cons_kg_per_capita']
fert['Date'] = fert['Year']
fert['boundary'] = 8.5

fert[fert['Date'] > 1999][final_col_list]

,domain,dimension,indicator,Date,value,boundary
39,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2000,94.653744,8.5
40,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2001,101.306518,8.5
41,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2002,91.977640,8.5
42,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2003,87.296534,8.5
43,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2004,96.765674,8.5
44,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2005,86.915325,8.5
45,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2006,79.932480,8.5
46,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2007,78.187997,8.5
47,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2008,70.188780,8.5
48,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2009,61.657537,8.5
49,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2010,71.952254,8.5
50,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2011,77.798474,8.5
51,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2012,77.936272,8.5
52,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2013,79.910847,8.5
53,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2014,88.367916,8.5
54,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2015,84.090690,8.5
55,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2016,90.210187,8.5
56,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2017,90.943844,8.5
57,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2018,86.528720,8.5
58,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2019,82.582067,8.5
59,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2020,101.125526,8.5
60,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2021,118.728271,8.5
61,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2022,104.610181,8.5
62,ecological,Nutrient Pollution,fertilizer_cons_kg_per_capita,2023,101.462221,8.5

In [64]:
fert[fert['Date'] > 1999][final_col_list].to_csv(input_path + "/ecological/clean/fertiliser_cons_clean.csv", 
                                                 index = False)

## Air Pollution
Air pollution is defined by the planetary boundaries as *"Asymmetry between Earth's hemispheres of sunlight reaching the surface, due to differences in atmospheric particle concentration"*. I don't have access to this data for Aus and so have chosen to adopt the WHO's guidelines for PM2.5 pollution as a boundary for air pollution. 

This is because there is documented evidence of negative health effects of PM2.5 pollution, that impacts humans, but also general particulate pollution flows through to the general *atmospheric particle concentration* outlined in the planetary boundary definition. This is again an incomplete and insufficient measure, but it's all i've got for now. 

The WHO recommends an annual concenrtation to stay below 5 micrograms of PM2.5. This will act as the boundary for this analysis.

PM2.5 Source: https://ourworldindata.org/grapher/average-exposure-pm25-pollution?tab=line&country=~AUS&mapSelect=~AUS
    - Global Burden of Disease Study 2023, Institute for Health Metrics and Evaluation (IHME), via World Bank (2026) – processed by Our World in Data

In [65]:
air = pd.read_csv(input_path + "/ecological/4_air_pollution/air_pollution_pm25_micrograms.csv")
air
air['domain'] = "ecological"
air['dimension'] = "Air Polution"
air['indicator'] = "Mean annual exposure cubic micrograms PM2.5"
air['value'] = air['PM2.5_pollution_mean_annual_exposure_micrograms_per_cubic_meter']
air['Date'] = air['Year']
air['boundary'] = 5

air[air['Date'] > 1999][final_col_list]

,domain,dimension,indicator,Date,value,boundary
10,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2000,6.206551,5
11,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2001,6.155016,5
12,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2002,6.390483,5
13,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2003,6.490767,5
14,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2004,5.801138,5
15,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2005,5.715543,5
16,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2006,6.034087,5
17,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2007,5.972216,5
18,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2008,6.047593,5
19,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2009,6.936861,5
20,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2010,5.291384,5
21,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2011,5.437967,5
22,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2012,5.396649,5
23,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2013,5.967594,5
24,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2014,6.040644,5
25,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2015,5.891992,5
26,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2016,5.824938,5
27,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2017,5.824313,5
28,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2018,6.054012,5
29,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2019,9.327339,5
30,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2020,6.813048,5
31,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2021,5.481868,5
32,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2022,5.302736,5
33,ecological,Air Polution,Mean annual exposure cubic micrograms PM2.5,2023,6.414739,5

In [66]:
air[air['Date'] > 1999][final_col_list].to_csv(input_path + "/ecological/clean/pm25_pollution_clean.csv", 
                                               index = False)

## Freshwater Disruption

It is possible that a data could be generated/extrapolated from a study like this: https://www.sciencedirect.com/science/article/pii/S0169204618304754.

However, I couldn't get access to the data to try extrapolate to all of Australia *(and I don't have the knowledge to do this accurately)*.

In [67]:
print("sad face")

sad face

## Land Conversion

Forests are essential for a planet that is hospitable to life. They promote biodiversity, watercycles provide nutrients to soil and store carbon whilst producing oxygen and other gases. Therefore, forest cover is a key planetary boundary. Therefore, the meausre adopted is the percentage of total area that is forested in Aus.

Source: https://databank.worldbank.org/source/world-development-indicators#

Based on this paper: https://academic.oup.com/jpe/article/5/1/109/1294916?login=false, it suggests around 30% of Australia was forested prior to the beginning colonisation in 1788. 

The v3 doughnut paper suggests the boundary is 75% of the pre-industrial forested area. So, 75% of 30% is 22.5% as the planetary boundary for this analysis.

In [68]:
land = pd.read_csv(input_path + "/ecological/6_land_conversion/forest_cover.csv")

land['domain'] = "ecological"
land['dimension'] = "Land Conversion"
land['indicator'] = "perc_land_forest_area"
land['value'] = land['perc_land_forest_area']
land['Date'] = land['Time']
land['boundary'] = 22.5


land[final_col_list]

,domain,dimension,indicator,Date,value,boundary
0,ecological,Land Conversion,perc_land_forest_area,2001,17.128633,22.5
1,ecological,Land Conversion,perc_land_forest_area,2002,17.099111,22.5
2,ecological,Land Conversion,perc_land_forest_area,2003,17.069589,22.5
3,ecological,Land Conversion,perc_land_forest_area,2004,17.040066,22.5
4,ecological,Land Conversion,perc_land_forest_area,2005,17.010544,22.5
5,ecological,Land Conversion,perc_land_forest_area,2006,16.981021,22.5
6,ecological,Land Conversion,perc_land_forest_area,2007,16.951499,22.5
7,ecological,Land Conversion,perc_land_forest_area,2008,16.921976,22.5
8,ecological,Land Conversion,perc_land_forest_area,2009,16.892454,22.5
9,ecological,Land Conversion,perc_land_forest_area,2010,16.862932,22.5
10,ecological,Land Conversion,perc_land_forest_area,2011,16.955310,22.5
11,ecological,Land Conversion,perc_land_forest_area,2012,17.047689,22.5
12,ecological,Land Conversion,perc_land_forest_area,2013,17.140067,22.5
13,ecological,Land Conversion,perc_land_forest_area,2014,17.232446,22.5
14,ecological,Land Conversion,perc_land_forest_area,2015,17.324825,22.5
15,ecological,Land Conversion,perc_land_forest_area,2016,17.425488,22.5
16,ecological,Land Conversion,perc_land_forest_area,2017,17.422914,22.5
17,ecological,Land Conversion,perc_land_forest_area,2018,17.421315,22.5
18,ecological,Land Conversion,perc_land_forest_area,2019,17.421315,22.5
19,ecological,Land Conversion,perc_land_forest_area,2020,17.421315,22.5
20,ecological,Land Conversion,perc_land_forest_area,2021,17.421315,22.5
21,ecological,Land Conversion,perc_land_forest_area,2022,17.421315,22.5
22,ecological,Land Conversion,perc_land_forest_area,2023,17.421315,22.5

In [69]:
land[final_col_list].to_csv(input_path + "/ecological/clean/forest_cover_clean.csv", index = False)

## Biodiversity Breakdown 

Biodiversity plays a key role in the complex web of ecology that ensures a liveable and hospitable planet. Species extinction is at the fastest rate in all of human history. 

Unfortunately, there doesn't seem to be a specific time series dataset of exctinctions in Australia. So, I've had to resort to the incomplete data for the number of "threatened" species available in the world development indicators database.

Source: https://databank.worldbank.org/source/world-development-indicators#

Specifically, it counts the number of threatened Bird, Fish, Mammal and plant species. This data is obviously very incomplete but it's all i've been able to find.

The boundary for this is zero i.e. no threatened species. Unfortuntaly because this cannot be easily transformed into an overshoot figure without some baseline value, I have excluded this data from the final analysis *(for now)*.

In [70]:
species = pd.read_csv(input_path + "/ecological/7_biodiversity_breakdown/species_threatened.csv")
species.columns
species['domain'] = "ecological"
species['dimension'] = "Land Conversion"
species['indicator'] = "num_species_threatened"
species['value'] = species[['Bird species, threatened [EN.BIR.THRD.NO]',
                            'Fish species, threatened [EN.FSH.THRD.NO]',
                            'Mammal species, threatened [EN.MAM.THRD.NO]',
                            'Plant species (higher), threatened [EN.HPT.THRD.NO]']].sum(axis = 1)
species['boundary'] = 0
species['Date'] = species['Time']

species[final_col_list]

       domain        dimension               indicator  Date  value  boundary
0  ecological  Land Conversion  num_species_threatened  2018    348         0
1  ecological  Land Conversion  num_species_threatened  2022   1115         0

In [71]:
species[final_col_list].to_csv(input_path + "/ecological/clean/threatened_species_clean.csv", index = False)

## Ozone Layer Depletion

The specific boundary of ozone depletion can really only be measured at the global level. The v3 doughnut paper uses dobson units. So it's hard to translate this specifically to the ozone depletion in/over Aus *(gases don't care about borders)*.

Therefore, to proxy for this i've decided to use the consumption of ozone depleting substances in Australia. There isn't a hard set boundary *(at least that I could find)* for a "Safe" level of ozone depleting substances to consume. However, because these were synthetic substances made i'm just going to infer that both the boundary is zero consumption of these substances. 

Ozone depleting substances include gases such as:
- Methyl Chloroform
- Methyl Bromide
- Hydrochlorofluorocarbons (HCFCs)
- Carbon Tetrachloride
- Halons
- Chlorofluorocarbons (CFCs)

Source:https://ourworldindata.org/grapher/ozone-depleting-substance-consumption?country=~AUS

Unfortunately, without an obviously baseline value this series cannot be easily transformed into an overshoot figure without some baseline value, I have excluded this data from the final analysis *(for now)*.

In [72]:
ozone = pd.read_csv(input_path + "/ecological/8_ozone_layer_depletion/ozone_depleting_substance_consumption.csv")
ozone.columns
ozone['domain'] = "ecological"
ozone['dimension'] = "Ozone Layer Depletion"
ozone['indicator'] = "ozone_depleting_subst_consump"
ozone['value'] = ozone[['Methyl Chloroform', 
                        'Methyl Bromide',
                        'Hydrochlorofluorocarbons (HCFCs)',
                        'Carbon Tetrachloride',
                        'Halons',
                        'Chlorofluorocarbons (CFCs)']].sum(axis = 1)
ozone['boundary'] = 0
ozone['Date'] = ozone['Year']

ozone[ozone['Date'] > 1999][final_col_list]

,domain,dimension,indicator,Date,value,boundary
12,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2000,484.60,0
13,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2001,360.80,0
14,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2002,389.70,0
15,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2003,278.90,0
16,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2004,189.80,0
17,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2005,171.00,0
18,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2006,69.40,0
19,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2007,86.60,0
20,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2008,68.40,0
21,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2009,57.20,0
22,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2010,-6.40,0
23,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2011,46.81,0
24,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2012,-33.51,0
25,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2013,48.62,0
26,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2014,10.10,0
27,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2015,17.19,0
28,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2016,11.28,0
29,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2017,10.52,0
30,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2018,17.41,0
31,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2019,14.84,0
32,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2020,16.04,0
33,ecological,Ozone Layer Depletion,ozone_depleting_subst_consump,2021,7.96,0

In [73]:
ozone[ozone['Date'] > 1999][final_col_list].to_csv(input_path + "/ecological/clean/ozone_clean.csv", 
                                                   index = False)